name: ğŸŒ Terraform Automation

on:
  push:
    branches:
        - feature/*
        - dev
        
env:
  TF_VAR_subscription_id: ${{secrets.SUBSCRIPTION_ID}}
  ARM_SUBSCRIPTION_ID: ${{secrets.SUBSCRIPTION_ID}}
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ğŸ§© HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.0
      
      - name: ğŸ”‘ Login to Azure
        id: az-login
        run: az login

      - name: ğŸ—ï¸ Terraform 
        id: init
        run: |
          cd terraform || exit 1 
          terraform init -input=false
          # terraform destroy -auto-approve
          terraform plan -out=tfplan 
          terraform apply -auto-approve tfplan
          cd ..
